name: Fuzzing Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}

    - name: Set up Python
      uses: actions/setup-python@v5

  fuzz:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask atheris
    - name: Run fuzzing test
      run: python fuzz_test.py -max_total_time=300
    - name: Check for crashes
      run: |
        mkdir -p fuzzing_results
        if [ -d "crash-" ]; then
          mv crash-* fuzzing_results/
          echo "Crashes found! Check the artifacts."
          exit 1
        else
          echo "No crashes found." > fuzzing_results/summary.txt
        fi
    - name: Upload fuzzing results
      uses: actions/upload-artifact@v3
      with:
        name: fuzzing-results
        path: fuzzing_results